#!/bin/bash

set -e

#EXTRA#
#DEBHELPER#

if [ -d "/etc/php5/mods-available" ]; then
    inidir=/etc/php5/mods-available/
else
    inidir=/etc/php5/conf.d/
fi

module=kolabformat
package=php-${module}
inifile=${module}.ini

if [ "$1" = "remove" ]; then
    if [ -x "$(which php5dismod 2>/dev/null)" ]; then
    	php5dismod ${module}
    elif [ -f "${inidir}/${inifile}" ]; then
        rm -f "${inidir}/${inifile}"
    fi
fi

exit 0
